-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    isSeller BOOLEAN NOT NULL,
    photo VARCHAR(255)
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL, 
    price DECIMAL(12,2) NOT NULL,
    description VARCHAR(15000) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);
-- can have multiple product files (images, videos, etc.) referencing a single product
-- url to file upload

CREATE TABLE ProductFiles ( 
    pid INT NOT NULL REFERENCES Products(id),
    url VARCHAR(255) NOT NULL,
    index INT NOT NULL,-- Used to order product files 
    type VARCHAR(4) CHECK (type IN ('IMG', 'VID'))
);

CREATE TABLE ProductCategories ( 
    cid INT NOT NULL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE ProductCategoriesLink (
    pid INT NOT NULL REFERENCES Products(id),
    cid INT NOT NULL REFERENCES ProductCategories(cid),
    PRIMARY KEY (pid, cid)
);

CREATE TABLE ProductOwner (
    pid INT NOT NULL REFERENCES Products(id),
    uid INT NOT NULL REFERENCES Users(id),
    PRIMARY KEY (pid, uid)
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'America/New_York')
);

CREATE TABLE Inventory (
    user_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL,
    PRIMARY KEY(user_id, product_id)
);

CREATE TABLE Seller_Reviews (
    id int not null primary key generated by default as identity,
    user_id int not null references Users(id),
    time_reviewed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'America/New_York'),
    comments varchar(2000) not null,
    num_stars INT CHECK (num_stars >= 1 AND num_stars <= 5),
    seller_id int not null references Users(id)
);

CREATE TABLE Product_Reviews (
    id int not null primary key generated by default as identity,
    user_id int not null references Users(id),
    time_reviewed timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'America/New_York'),
    comments varchar(2000) not null,
    num_stars INT CHECK (num_stars >= 1 AND num_stars <= 5),
    product_id int not null references Products(id)
);

-- CREATE TABLE SellerReviewFiles ( 
--     review_id INT NOT NULL REFERENCES Seller_Reviews(id),
--     url VARCHAR(255) NOT NULL,
--     index INT NOT NULL,-- Used to order product files 
--     type VARCHAR(4) CHECK (type IN ('IMG', 'VID'))
-- );

-- CREATE TABLE ProductReviewFiles ( 
--     review_id INT NOT NULL REFERENCES Product_Reviews(id),
--     url VARCHAR(255) NOT NULL,
--     index INT NOT NULL,-- Used to order product files 
--     type VARCHAR(4) CHECK (type IN ('IMG', 'VID'))
-- );

CREATE TABLE Cart (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT NOT NULL REFERENCES Users(id),
    product_id INT NOT NULL REFERENCES Products(id),
    seller_id INT NOT NULL REFERENCES Users(id),
    quantity INT NOT NULL,
    saved BOOLEAN DEFAULT FALSE,
    order_id INT DEFAULT NULL,
    fulfilled BOOLEAN DEFAULT FALSE,
    time_fulfilled timestamp without time zone DEFAULT Null
);


CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INT REFERENCES Users(id),
    fulfilled BOOLEAN DEFAULT FALSE,
    time_ordered timestamp without time zone DEFAULT (current_timestamp AT TIME ZONE 'America/New_York'),
    delivery_addy VARCHAR(255) DEFAULT NULL
);


CREATE TABLE Balance (
    user_id INT NOT NULL REFERENCES Users(id),
    amount DECIMAL NOT NULL
);
